/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fabi' at '06/05/16 10:25 AM' with Gradle 2.12
 *
 * @author fabi, @date 06/05/16 10:25 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
