import org.junit.Test;

import static com.jayway.awaitility.Awaitility.await;
import static java.util.concurrent.TimeUnit.SECONDS;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'fabi' at '06/05/16 10:25 AM' with Gradle 2.12
 *
 * @author fabi, @date 06/05/16 10:25 AM
 */
public class ServiceTest {
    @Test
    public void doWork() {
        Service service = AkkaSystem.getServiceActor();
        await().atMost(5, SECONDS).until(() -> service.doAllWork().isCompleted());
    }


}
