import org.junit.Test;

import static com.jayway.awaitility.Awaitility.await;
import static java.util.concurrent.TimeUnit.SECONDS;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'fabi' at '06/05/16 10:25 AM' with Gradle 2.12
 *
 * @author fabi, @date 06/05/16 10:25 AM
 */
public class ServiceTest {
    @Test
    public void doWork() {
        Service service = AkkaSystem.getServiceActor();
        service.doSomeWork();
        await().atMost(5, SECONDS).untilTrue(service.isBusy());
        await().atMost(10, SECONDS).untilFalse(service.isBusy());
    }

    @Test
    public void queueWork() {
        ServiceController controller = AkkaSystem.getServiceControllerActor();
        Service service = AkkaSystem.getServiceActor();
        assertThat(controller.addWork(), is(true));
        assertThat(controller.addWork(), is(false));
        await().atMost(10, SECONDS).untilFalse(service.isBusy());
    }


}
